### PR TITLE
update to be ember 2.1 friendly

### PR DESCRIPTION
**Pull request by toranb**
This solved the issues we found with ember 2.1 beta 2 and beta 3

### CODE REVIEW

**Comment by jamesarosen** [comment]
Merged & closed (with a tiny change from `var` to `const`)

**Comment by toranb** [comment]
excellent! thanks again @jamesarosen

**Comment by toranb** [comment]
Any plan to publish a release w/ this by the end of next week?

**Comment by jamesarosen** [comment]
Yeah, maybe this weekend. It depends on other PRs. If nothing else is ready, I'll just do this as a minor patch.

**Comment by toranb** [comment]
Sounds good! Thanks again

**Comment by jamesarosen** [comment]
Released as 4.1.3

**Comment by toranb** [comment]
Awesome! worked perfectly :)

**Pull request closed without merging**
