### PR TITLE
Add support for automatically choosing different i18n keys for different countries

### PR DESCRIPTION
**Pull request by inez**
Example: if countryCode is set to RU then lookup keys in order: <key>.RU, <key>.default, <key>

### CODE REVIEW

**Comment by toranb** [comment]
Whoa ... so this PR has just hung (green) since Apr 10th 2017 without any activity ?!??

@inez can you confirm that what I've done w/ missing message accomplishes the same goal you are trying to add here?

note: obviously mine is way more of a hack atm ;) and doesn't support a full template compile

^if so ... what do we need to land this? I've been asking around and it seems this would be a no-brainier to add #am_i_rite

**Comment by toranb** [comment]
Ah, disregard that comment seems this is for defaults within a single locale ...

@snewcomer @jamesarosen you guys know of anyone who has tried to add support for a "default" fallback like I did in that gist above?!??

**Comment by toranb** [comment]
ah looks like #386 is what I was after! I'll skip out of this PR and read up on that one

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).

**Pull request closed without merging**
