### PR TITLE
Add Ember alpha version support

### PR DESCRIPTION
**Pull request by Cryrivers**

### CODE REVIEW

**Comment by jamesarosen** [comment]
This is fine to merge as-is.

I would _really_ like to figure out a way to get the whole legacy-helper _out_ of the compiled code on newer Ember environments so we don't have to keep patching the stream stuff on environments that don't even use it.

**Comment by Cryrivers** [comment]
One more thing I found is that data passed into the helper `t` could be an `EmptyObject` in Glimmer 2, which does not have `hasOwnProperty` function. So lines of code below will fail.

```javascript
Ember.deprecate('locale is a reserved attribute', !data.hasOwnProperty('locale'), {
    id: 'ember-i18n.reserve-locale'
});
Ember.deprecate('htmlSafe is a reserved attribute', !data.hasOwnProperty('htmlSafe'), {
    id: 'ember-i18n.reserve-htmlSafe'
});
```

**Comment by workmanw** [comment]
I'm not sure if this is the right place to bring this up, but since this called "Add Ember alpha version", I'll go for it. I'm getting exceptions trying to use `{{translateAttr}}` with Ember alpha. Here is the stack:

```
on-error.js:77 Error: Compile Error: translateAttr is not a modifier
    at Modifier.compile (ember.debug.js:47928)
    at InlineBlockCompiler.compileStatement (ember.debug.js:45681)
    at InlineBlockCompiler.compile (ember.debug.js:45756)
    at InlineBlock.compile (ember.debug.js:42086)
    at VM.invokeBlock (ember.debug.js:49540)
    at OpenBlockOpcode.evaluate (ember.debug.js:48470)
    at VM.execute (ember.debug.js:49521)
    at TryOpcode.handleException (ember.debug.js:49942)
    at UpdatingVMFrame.handleException (ember.debug.js:50125)
    at UpdatingVM._throw [as throw] (ember.debug.js:49834)
```

**Comment by jamesarosen** [comment]
> I would really like to figure out a way to get the whole legacy-helper out of the compiled code on newer Ember environments so we don't have to keep patching the stream stuff on environments that don't even use it.

#392 is my attempt at this, but it's blocked.

**Comment by Cryrivers** [comment]
As master branch supported 2.9 beta already, I'm closing this PR.

**Pull request closed without merging**
