### PR TITLE
upgrade ember-cli-qunit

### PR DESCRIPTION
**Pull request by jamesarosen**
See switchfly/ember-test-helpers#59 and switchfly/ember-test-helpers#79

### CODE REVIEW

**Comment by jamesarosen** [comment]
@rwjblue this is the change I mentioned in Slack. I haven't been able to diagnose the new problem because the stack trace is all in Backburner.

**Comment by rwjblue** [comment]
Just released ember-qunit@0.4.2 with compat for Ember 2.0.0-beta.3.

**Comment by blimmer** [comment]
@jamesarosen I think you can close this because I did all the upgrades (including ember-cli 1.13.1) in #276

**Comment by jamesarosen** [comment]
Blocked by #284

**Comment by rwjblue** [comment]
I believe that this was superceded by https://github.com/jamesarosen/ember-i18n/pull/276.

**Pull request closed without merging**
