### PR TITLE
replace innerHtml with textContent

### PR DESCRIPTION
**Pull request by snewcomer**
Forgot one.  Possible to get a patch upgrade after this PR! 

Note: used helper on a lg test suite and everything worked great!

### CODE REVIEW

**Comment by jamesarosen** [comment]
> Possible to get a patch upgrade after this PR!

I'm wondering whether the change from `:contains` to `textContent` means it has to be a _major_ version bump.

**Comment by snewcomer** [comment]
Hm.  Yeah you may be right.  A user could explicitly import this helper in the old testing API's and it would fail if they haven't migrated to the new testing API's (`@ember/test-helpers` specifically).  However, if users have migrated to the new testing API's, it is safe to assume they have gotten rid of `:contains` selectors...

**Comment by jamesarosen** [comment]
Specifically, I'm thinking of the difference between [before](https://github.com/jamesarosen/ember-i18n/pull/475/files#diff-b37a555760fbeb3f7e4ce23503aad541L21) and [after](https://github.com/jamesarosen/ember-i18n/pull/475/files#diff-8251a387fb0a902445da9f3e5991e6afR6).

**Comment by snewcomer** [comment]
Ah yes.  Anybody still on the old testing API's will see a failure.  I guess that would constitute a major bump!

**Pull request merged**
