### PR TITLE
Modernize addon

### PR DESCRIPTION
**Pull request by cibernox**
I tried to contribute but I just can't run the addon locally anymore. I suspect that is because some incompatibility between one dependency and node > 4. It wouldn't even install.

I just decided to update ember-cli from 1.13 to 2.11 and say `YES` to almost everything.
Things to note:

- The recommended test matrix in ember-cli is not 2.4+. This would remove 1.13 support officially. Nothing makes me thing it doesn't work anymore, but it would be untested. I think that at this point is fine to remove 1.13.

### CODE REVIEW

**Comment by jamesarosen** [comment]
I don't love removing the 1.13 tests in v4.x. Maybe this is the beginning of the v5 branch?

**Comment by cibernox** [comment]
@jamesarosen Do I need to address something else on this PR to get it merged? Once merged I'll rebase and fix #431

**Comment by cibernox** [comment]
Rebased and solved conflicts

**Comment by cibernox** [comment]
@jamesarosen Any update on this?

**Comment by jamesarosen** [comment]
Go for it. Let's start the process of v5. (For one, let's make 5080d0909d683cf084b73ab27b021a85d6db5fd0 the tip of a v4-stable branch.)

**Comment by cibernox** [comment]
@jamesarosen Is there something else I have to do? I can't merge or create tags.

**Comment by cibernox** [comment]
I've just published 5.0.0. Hopefully there is no errors

**Pull request merged**
