### PR TITLE
Stop setting Chinese as the default.

### PR DESCRIPTION
**Pull request by nathanhammond**
We should be using a private use language subtag.

### CODE REVIEW

**Comment by jamesarosen** [comment]
I love it

**Comment by nathanhammond** [comment]
Didn't forget, just discovered that doing it in the GitHub UI required me to do it in two commits. 😜

**Comment by jamesarosen** [comment]
> is this going to be a major version update though?

It doesn't feel like a breaking API change to me. I'm open to arguments either way.

**Comment by mehulkar** [comment]
I guess since the implementation is the same as the implementation for `zh`, it's not a breaking change! 

The only case where this might break people is if they've overriden `zh` config specifically, and then encounter a locale that isn't included in this package. (For me, for example, I defined a config for `el-gr`, which is what triggerred @nathanhammond's PR)

**Pull request merged**
